# Local Development Configuration for Hero365
# This file extends the base config.toml for local development

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000", "http://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
enable_confirmations = false
double_confirm_changes = false
secure_password_change = false

[auth.sms]
enable_signup = true
enable_confirmations = false

[auth.external.apple]
enabled = true
client_id = ""
secret = ""

[auth.external.google]
enabled = true
client_id = ""
secret = ""

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB" 