/**
 * API Configuration
 * 
 * Centralized configuration for API endpoints that adapts to different environments
 */

export interface ApiConfig {
  baseUrl: string;
  apiVersion: string;
  timeout: number;
  retries: number;
  environment: 'development' | 'staging' | 'production';
}

export interface EnvironmentConfig {
  api: ApiConfig;
  features: {
    analytics: boolean;
    voiceAgent: boolean;
    bookingWidget: boolean;
    errorReporting: boolean;
  };
  business: {
    defaultBusinessId: string;
    defaultBusinessName: string;
    defaultBusinessPhone: string;
    defaultBusinessEmail: string;
  };
}

/**
 * Get the current environment
 */
function getEnvironment(): 'development' | 'staging' | 'production' {
  if (typeof window === 'undefined') {
    // Server-side: use NODE_ENV
    return (process.env.NODE_ENV as any) || 'development';
  }
  
  // Client-side: detect from hostname
  const hostname = window.location.hostname;
  
  if (hostname === 'localhost' || hostname === '127.0.0.1' || hostname.startsWith('192.168.')) {
    return 'development';
  } else if (hostname.includes('staging') || hostname.includes('dev') || hostname.includes('preview')) {
    return 'staging';
  } else {
    return 'production';
  }
}

/**
 * Get API base URL based on environment
 */
function getApiBaseUrl(environment: string): string {
  // Check for explicit environment variable first (highest priority)
  if (typeof process !== 'undefined' && process.env.NEXT_PUBLIC_API_URL) {
    return process.env.NEXT_PUBLIC_API_URL;
  }
  
  // Environment-specific defaults
  switch (environment) {
    case 'development':
      return 'http://localhost:8000';  // Global default for development
    
    case 'staging':
      return process.env.NEXT_PUBLIC_STAGING_API_URL || 'https://api-staging.hero365.ai';
    
    case 'production':
      return process.env.NEXT_PUBLIC_PRODUCTION_API_URL || 'https://api.hero365.ai';
    
    default:
      return 'http://localhost:8000';  // Fallback to localhost
  }
}

/**
 * Create environment-specific configuration
 */
function createEnvironmentConfig(): EnvironmentConfig {
  const environment = getEnvironment();
  const baseUrl = getApiBaseUrl(environment);
  
  return {
    api: {
      baseUrl: baseUrl.includes('/api/v1') ? baseUrl : `${baseUrl}/api/v1`,
      apiVersion: 'v1',
      timeout: environment === 'development' ? 30000 : 15000,
      retries: environment === 'development' ? 1 : 3,
      environment
    },
    features: {
      analytics: process.env.NEXT_PUBLIC_ANALYTICS_ENABLED !== 'false',
      voiceAgent: process.env.NEXT_PUBLIC_VOICE_AGENT_ENABLED === 'true',
      bookingWidget: process.env.NEXT_PUBLIC_BOOKING_WIDGET_ENABLED !== 'false',
      errorReporting: environment === 'production'
    },
    business: {
      defaultBusinessId: process.env.NEXT_PUBLIC_DEFAULT_BUSINESS_ID || '123e4567-e89b-12d3-a456-426614174000',
      defaultBusinessName: process.env.NEXT_PUBLIC_DEFAULT_BUSINESS_NAME || 'Elite HVAC Services',
      defaultBusinessPhone: process.env.NEXT_PUBLIC_DEFAULT_BUSINESS_PHONE || '+1-555-123-4567',
      defaultBusinessEmail: process.env.NEXT_PUBLIC_DEFAULT_BUSINESS_EMAIL || 'contact@elitehvac.com'
    }
  };
}

// Global configuration instance
let configInstance: EnvironmentConfig | null = null;

/**
 * Get the current configuration
 */
export function getConfig(): EnvironmentConfig {
  if (!configInstance) {
    configInstance = createEnvironmentConfig();
  }
  return configInstance;
}

/**
 * Reset configuration (useful for testing)
 */
export function resetConfig(): void {
  configInstance = null;
}

/**
 * Get API configuration
 */
export function getApiConfig(): ApiConfig {
  return getConfig().api;
}

/**
 * Get feature flags
 */
export function getFeatures() {
  return getConfig().features;
}

/**
 * Get business configuration
 */
export function getBusinessConfig() {
  // Check for environment variables first (set by deployment script)
  if (typeof process !== 'undefined') {
    const envBusinessId = process.env.NEXT_PUBLIC_BUSINESS_ID;
    const envBusinessName = process.env.NEXT_PUBLIC_BUSINESS_NAME;
    const envBusinessPhone = process.env.NEXT_PUBLIC_BUSINESS_PHONE;
    const envBusinessEmail = process.env.NEXT_PUBLIC_BUSINESS_EMAIL;
    
    if (envBusinessId) {
      return {
        defaultBusinessId: envBusinessId,
        defaultBusinessName: envBusinessName || 'Professional Services',
        defaultBusinessPhone: envBusinessPhone || '+1-555-123-4567',
        defaultBusinessEmail: envBusinessEmail || 'contact@example.com'
      };
    }
  }
  
  // Try to load business-specific configuration file
  if (typeof window !== 'undefined') {
    try {
      // This would be generated by the deployment script
      const businessConfigPath = '/config/business-config.json';
      // Note: In a real implementation, you'd fetch this or have it embedded
      // For now, fall back to default config
    } catch (error) {
      // Fall back to default configuration
    }
  }
  
  return getConfig().business;
}

/**
 * Get the current business ID
 */
export function getCurrentBusinessId(): string {
  const businessConfig = getBusinessConfig();
  return businessConfig.defaultBusinessId;
}

/**
 * Build API URL for a specific endpoint
 */
export function buildApiUrl(endpoint: string): string {
  const config = getApiConfig();
  const cleanEndpoint = endpoint.startsWith('/') ? endpoint.slice(1) : endpoint;
  const fullUrl = `${config.baseUrl}/${cleanEndpoint}`;
  console.log('🔧 [DEBUG] buildApiUrl:', { 
    baseUrl: config.baseUrl, 
    endpoint, 
    cleanEndpoint, 
    fullUrl,
    environment: config.environment 
  });
  return fullUrl;
}

/**
 * Build public API URL (no authentication required)
 */
export function buildPublicApiUrl(endpoint: string): string {
  const cleanEndpoint = endpoint.startsWith('/') ? endpoint.slice(1) : endpoint;
  const fullUrl = buildApiUrl(`public/${cleanEndpoint}`);
  console.log('🔧 [DEBUG] buildPublicApiUrl:', { endpoint, cleanEndpoint, fullUrl });
  return fullUrl;
}

/**
 * Build authenticated API URL (authentication required)
 */
export function buildAuthApiUrl(endpoint: string): string {
  const cleanEndpoint = endpoint.startsWith('/') ? endpoint.slice(1) : endpoint;
  return buildApiUrl(cleanEndpoint);
}

/**
 * Check if we're in development mode
 */
export function isDevelopment(): boolean {
  return getConfig().api.environment === 'development';
}

/**
 * Check if we're in production mode
 */
export function isProduction(): boolean {
  return getConfig().api.environment === 'production';
}

/**
 * Get the backend API base URL (without /api/v1 path)
 * This is the global setting for all API calls
 */
export function getBackendUrl(): string {
  const environment = getEnvironment();
  return getApiBaseUrl(environment);
}

/**
 * Get environment-specific headers
 */
export function getDefaultHeaders(): Record<string, string> {
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
  };

  // Add environment-specific headers
  if (isDevelopment()) {
    headers['X-Environment'] = 'development';
  }

  // Add version header
  headers['X-API-Version'] = getApiConfig().apiVersion;

  return headers;
}

/**
 * Configuration for different deployment environments
 */
export const DEPLOYMENT_CONFIGS = {
  development: {
    apiUrl: 'http://localhost:8000',
    websiteUrl: 'http://localhost:3001',
    features: {
      analytics: false,
      errorReporting: false,
      debugMode: true
    }
  },
  staging: {
    apiUrl: 'https://api-staging.hero365.ai',
    websiteUrl: 'https://staging.hero365.ai',
    features: {
      analytics: true,
      errorReporting: true,
      debugMode: true
    }
  },
  production: {
    apiUrl: 'https://api.hero365.ai',
    websiteUrl: 'https://hero365.ai',
    features: {
      analytics: true,
      errorReporting: true,
      debugMode: false
    }
  }
} as const;

export default getConfig;
