export interface ContentField {
  type: 'text' | 'textarea' | 'email' | 'phone' | 'array' | 'boolean' | 'object';
  required?: boolean;
  default?: any;
  generate?: boolean; // Should be generated by AI
}

export interface ContentFields {
  [key: string]: ContentField | { [key: string]: ContentField };
}

export interface PageSection {
  component: string;
  props: string; // Reference to content field key
}

export interface Page {
  path: string;
  name: string;
  sections: PageSection[];
}

export interface ThemeConfig {
  primaryColor: string;
  secondaryColor: string;
  fontFamily: string;
}

export interface TemplateConfig {
  id: string;
  trade: string;
  category: 'COMMERCIAL' | 'RESIDENTIAL' | 'BOTH';
  name: string;
  description: string;
  contentFields: ContentFields;
  pages: Page[];
  theme: ThemeConfig;
}
