"""
API Schemas Package

Request/Response schemas for API endpoints.
"""

from .activity_schemas import (
    ActivityResponse,
    ActivityCreateRequest,
    ActivityUpdateRequest,
    ActivitySearchRequest,
    ActivityListResponse,
    ActivityTemplateResponse,
    ActivityTemplateCreateRequest,
    TimelineResponse,
    ActivityStatisticsResponse,
)
from .auth_schemas import (
    RegisterRequest,
    LoginRequest,
    AuthUserResponse,
    ResetPasswordRequest,
    AuthTokenResponse,
    AppleSignInRequest,
    GoogleSignInRequest,
    OAuthSignInResponse,
)
from .business_schemas import (
    BusinessResponse,
    BusinessCreateRequest,
    BusinessUpdateRequest,
    BusinessSummaryResponse,
    BusinessSearchRequest,
    BusinessMembershipResponse,
    BusinessInvitationResponse,
    BusinessInvitationCreateRequest,
    BusinessStatsResponse,
)
from .contact_schemas import (
    ContactResponse,
    ContactCreateRequest,
    ContactUpdateRequest,
    ContactSearchRequest,
    ContactListResponse,
    ContactInteractionResponse,
    ContactInteractionCreateRequest,
    ContactStatusUpdateRequest,
    ContactStatisticsResponse,
)
from .job_schemas import (
    JobResponse,
    JobCreateRequest,
    JobUpdateRequest,
    JobSearchRequest,
    JobListResponse,
    JobStatisticsResponse,
    JobAssignmentRequest,
    JobStatusUpdateRequest,
    JobBulkUpdateRequest,
)
from .project_schemas import (
    ProjectResponse,
    ProjectCreateRequest,
    ProjectUpdateRequest,
    ProjectSearchRequest,
    ProjectListResponse,
    ProjectStatisticsResponse,
    ProjectAssignmentRequest,
    ProjectTemplateResponse,
    ProjectTemplateCreateRequest,
)
from .estimate_schemas import (
    EstimateResponseSchema,
    CreateEstimateSchema,
    UpdateEstimateSchema,
    EstimateSearchSchema,
    EstimateListResponseSchema,
    EstimateStatusUpdateSchema,
    EstimateLineItemSchema,
    EstimateTermsSchema,
    AdvancePaymentSchema,
)
from .invoice_schemas import (
    InvoiceResponseSchema,
    CreateInvoiceSchema,
    CreateInvoiceFromEstimateSchema,
    ProcessPaymentSchema,
    InvoiceSearchSchema,
    InvoiceListResponseSchema,
    InvoiceStatusUpdateSchema,
    InvoiceLineItemSchema,
    PaymentSchema,
)
from .product_schemas import (
    ProductResponseSchema,
    CreateProductSchema,
    UpdateProductSchema,
    ProductSummarySchema,
    ProductSearchSchema,
    ProductListResponseSchema,
    StockAdjustmentSchema,
    StockMovementResponseSchema,
    ReorderSuggestionSchema,
    ReorderSuggestionsResponseSchema,
    ProductActionResponse,
    StockActionResponse,
    ProductPricingTierSchema,
    ProductLocationSchema,
    ProductSupplierSchema,
)

__all__ = [
    # Activity schemas
    "ActivityResponse",
    "ActivityCreateRequest",
    "ActivityUpdateRequest",
    "ActivitySearchRequest",
    "ActivityListResponse",
    "ActivityTemplateResponse",
    "ActivityTemplateCreateRequest",
    "TimelineResponse",
    "ActivityStatisticsResponse",
    # Auth schemas
    "RegisterRequest",
    "LoginRequest",
    "AuthUserResponse",
    "ResetPasswordRequest",
    "AuthTokenResponse",
    "AppleSignInRequest",
    "GoogleSignInRequest",
    "OAuthSignInResponse",
    # Business schemas
    "BusinessResponse",
    "BusinessCreateRequest",
    "BusinessUpdateRequest",
    "BusinessSummaryResponse",
    "BusinessSearchRequest",
    "BusinessMembershipResponse",
    "BusinessInvitationResponse",
    "BusinessInvitationCreateRequest",
    "BusinessStatsResponse",
    # Contact schemas
    "ContactResponse",
    "ContactCreateRequest",
    "ContactUpdateRequest",
    "ContactSearchRequest",
    "ContactListResponse",
    "ContactInteractionResponse",
    "ContactInteractionCreateRequest",
    "ContactStatusUpdateRequest",
    "ContactStatisticsResponse",
    # Job schemas
    "JobResponse",
    "JobCreateRequest",
    "JobUpdateRequest",
    "JobSearchRequest",
    "JobListResponse",
    "JobStatisticsResponse",
    "JobAssignmentRequest",
    "JobStatusUpdateRequest",
    "JobBulkUpdateRequest",
    # Project schemas
    "ProjectResponse",
    "ProjectCreateRequest",
    "ProjectUpdateRequest",
    "ProjectSearchRequest",
    "ProjectListResponse",
    "ProjectStatisticsResponse",
    "ProjectAssignmentRequest",
    "ProjectTemplateResponse",
    "ProjectTemplateCreateRequest",
    # Estimate schemas
    "EstimateResponseSchema",
    "CreateEstimateSchema",
    "UpdateEstimateSchema",
    "EstimateSearchSchema",
    "EstimateListResponseSchema",
    "EstimateStatusUpdateSchema",
    "EstimateLineItemSchema",
    "EstimateTermsSchema",
    "AdvancePaymentSchema",
    # Invoice schemas
    "InvoiceResponseSchema",
    "CreateInvoiceSchema",
    "CreateInvoiceFromEstimateSchema",
    "ProcessPaymentSchema",
    "InvoiceSearchSchema",
    "InvoiceListResponseSchema",
    "InvoiceStatusUpdateSchema",
    "InvoiceLineItemSchema",
    "PaymentSchema",
    # Product schemas
    "ProductResponseSchema",
    "CreateProductSchema",
    "UpdateProductSchema",
    "ProductSummarySchema",
    "ProductSearchSchema",
    "ProductListResponseSchema",
    "StockAdjustmentSchema",
    "StockMovementResponseSchema",
    "ReorderSuggestionSchema",
    "ReorderSuggestionsResponseSchema",
    "ProductActionResponse",
    "StockActionResponse",
    "ProductPricingTierSchema",
    "ProductLocationSchema",
    "ProductSupplierSchema",
] 