name = "hero365-professional-website"
compatibility_date = "2024-01-25"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "hero365-professional-website"

[env.preview]  
name = "hero365-professional-website-preview"

# Pages configuration
[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "modules"
dir = "./out"

# Custom domain configuration (optional)
# [env.production.route]
# pattern = "*.yourdomain.com/*"

# Environment variables (if needed)
# [env.production.vars]
# API_URL = "https://api.hero365.ai"
