main = ".open-next/worker.js"
name = "hero365-website"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[env.production]
name = "hero365-website-production"

[env.preview]
name = "hero365-website-preview"

[env.staging]
name = "hero365-website-staging"

# Multi-tenant routing - configure domains as needed
# [env.production.routes]
# pattern = "*.hero365.app/*"
# zone_id = "YOUR_ZONE_ID"

# Environment variables
[vars]
NEXT_PUBLIC_API_URL = "https://api.hero365.ai"
NEXT_PUBLIC_API_VERSION = "v1"
NEXT_PUBLIC_DEBUG_MODE = "false"
NEXT_PUBLIC_ANALYTICS_ENABLED = "true"

[env.preview.vars]
NEXT_PUBLIC_API_URL = "https://api-preview.hero365.ai"
NEXT_PUBLIC_API_VERSION = "v1"
NEXT_PUBLIC_DEBUG_MODE = "true"
NEXT_PUBLIC_ANALYTICS_ENABLED = "false"

[env.staging.vars]
NEXT_PUBLIC_BUSINESS_ID = "550e8400-e29b-41d4-a716-446655440010"
NEXT_PUBLIC_BUSINESS_NAME = "Elite HVAC Austin"
NEXT_PUBLIC_BUSINESS_PHONE = ""
NEXT_PUBLIC_BUSINESS_EMAIL = ""
NEXT_PUBLIC_API_URL = "https://73d34a85b4db.ngrok-free.app"
NEXT_PUBLIC_API_VERSION = "v1"
NEXT_PUBLIC_DEBUG_MODE = "true"
NEXT_PUBLIC_ANALYTICS_ENABLED = "true"
NEXT_PUBLIC_ENVIRONMENT = "staging"
