name = "hero365-professional-website"
compatibility_date = "2024-01-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production]
name = "hero365-professional-website"

[env.preview]
name = "hero365-professional-website-preview"

# Pages configuration (build is done locally via build:ssr before deploy)

# Custom domain configuration (optional)
# [env.production.route]
# pattern = "*.yourdomain.com/*"

# Environment variables (if needed)
# [env.production.vars]
# API_URL = "https://api.hero365.ai"
