name = "hero365-contractors-webs"
compatibility_date = "2024-01-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production]
name = "hero365-contractors-webs"

[env.preview]  
name = "hero365-contractors-webs-preview"

# Pages configuration
# Note: Pages projects do not support [build] in wrangler.toml; build is run prior to deploy

# Custom domain configuration (optional)
# [env.production.route]
# pattern = "*.yourdomain.com/*"

# Environment variables (if needed)
# [env.production.vars]
# API_URL = "https://api.hero365.ai"
